apiVersion: v1
kind: Secret
metadata:
  name: memorywiki-secrets
type: Opaque
stringData:
  s3AccessKey: {{ .Values.secrets.s3AccessKey | quote }}
  s3SecretKey: {{ .Values.secrets.s3SecretKey | quote }}
  jwtSigningKey: {{ .Values.secrets.jwtSigningKey | quote }}
  openAiApiKey: {{ .Values.secrets.openAiApiKey | quote }}
