// <auto-generated />
using System;
using MemoryWiki.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemoryWiki.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MemoryWikiDbContext))]
partial class MemoryWikiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MemoryWiki.Domain.Entities.Transcript", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("ContentHash").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("FailureReason").HasColumnType("text");
            b.Property<string>("ObjectKey").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<long>("SizeBytes").HasColumnType("bigint");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.ToTable("transcripts");
        });

        modelBuilder.Entity("MemoryWiki.Domain.Entities.ProcessingJob", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<int>("Attempts").HasColumnType("integer");
            b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("IdempotencyKey").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("LastError").HasColumnType("text");
            b.Property<DateTimeOffset?>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<Guid>("TranscriptId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TranscriptId").IsUnique();
            b.ToTable("processing_jobs");
        });

        modelBuilder.Entity("MemoryWiki.Domain.Entities.MemoryDocument", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("ContentHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsDeleted").HasColumnType("boolean");
            b.Property<string>("ObjectKey").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<string>("Path").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<long>("SizeBytes").HasColumnType("bigint");
            b.Property<string>("Slug").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<string>("TenantId").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<int>("Type").HasColumnType("integer");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int>("Version").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("Path").IsUnique();
            b.HasIndex("Type", "IsDeleted");
            b.ToTable("memory_documents");
        });

        modelBuilder.Entity("MemoryWiki.Infrastructure.Persistence.AuditLog", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("Actor").HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("DataJson").HasColumnType("text");
            b.Property<string>("EntityId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("EntityType").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.HasKey("Id");
            b.HasIndex("CreatedAtUtc");
            b.ToTable("audit_logs");
        });
    }
}
